### ISSUE TITLE
The menu does not appear

### ISSUE THREAD

**Issue by limter1** [DragoSpiro98/stickerBot#1]
The list does not appear
When I send the command #MENU, I don't see a message
What is the problem I hope to solve
Thank you

**Comment by DragoSpiro98** [comment]
There is no menu, it is a whatsapp sticker bot, it must be activated, synchronized with your phone (when you have the active bot you cannot use WhatsApp Web) and if someone sends a photo with the message "#sticker", the bot processes the image and creates the sticker, same thing for videos using the #gif function

**Comment by DragoSpiro98** [comment]
I could add a menu function that shows all the functions of the bot. However, I stopped updating the bot because I used it to create animated stickers, but now it's possible to do it in a different way
