### ISSUE TITLE
sorry for writing here, how did you solve the problem?

### ISSUE THREAD

**Issue by Truyn** [DragoSpiro98/stickerBot#2]
sorry for writing here, how did you solve the problem?
https://github.com/pterodactyl/panel/issues/1321

**Comment by DragoSpiro98** [comment]
> sorry for writing here, how did you solve the problem?
> https://github.com/pterodactyl/panel/issues/1321

I don't remember, I recommend that you follow the entire guide all over again and read everything. If you follow the guide you shouldn't have any problems.
